# Use docker-based build environment (instead of openvz)
sudo: false

language: java

jdk:
  - oraclejdk8
  - oraclejdk11
  
services:
  - mysql
  - postgresql

cache:
  directories:
    - '$HOME/.m2/repository'

