udo: required
dist: trusty
group: edge

language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  
services:
  - mysql
  - postgresql

cache:
  directories:
    - '$HOME/.m2/repository'

before_script:
  - psql -c 'create database travis;' -U postgres

install: /bin/true